# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
install: true
script:
- mvn install

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  -bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -shynybaev@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    - CODEV_TOKEN= "792ff530-3f3b-432b-9b36-f5a4380f88a5"